#
# .travis.yml
#

language: cpp

compiler:
  - gcc

addons:
  apt:
    packages:
      - libhdf5-serial-dev

before_script:
  - wget https://github.com/UK-MAC/typhonio/archive/master.tar.gz
  - tar -zxvf master.tar.gz
  - pushd typhonio-master/src
  - make install HPC_COMPILER=gcc NOF90=1 CFLAGS=-DH5_NO_DEPRECATED_SYMBOLS
  - popd

script:
  - mkdir build \
    && cd build \
    && cmake ../travis_example -DTyphonIO_ROOT:PATH=../typhonio-master/build/gcc \
    && make
